---
title: "R: Line graph with a color gradient using ggplot2"
description: |
  This tutorial provides a way to plot a line graph with ggplot2 with a color gradient
preview: https://github.com/Yedomon/plastomics101/blob/main/pic1.png
author:
  - name: Yedomon Ange Bovys Zoclanclounon
    url: https://yedomon.netlify.app/
    affiliation: Jeonbuk National University
    affiliation_url: http://www.jbnu.ac.kr/eng/
    orcid_id: 0000-0003-2781-0778
date: 01-10-2021

self_contained: false

output:
  distill::distill_article:
    toc: true
    theme: theme.css
    name: "line-plot-color-gradient-ggplot2"
base_url: https://yedomon.netlify.app/posts/2021-01-10-line-plot-color-gradient-ggplot2/
creative_commons: CC BY
---



```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```



### Brainstorming

The purpose here is to plot a line graph that shows the nucleotide diversity (Pi) alongside a chloroplast genome. More specifically, we want to emphasis using a gradient color a certain value up to a threshold (here **0.015**).

Let's get into it!

### Solution

#### Package loading

```{r, code_folding=TRUE, echo=TRUE}

library(ggplot2)

```


#### Data importaion

```{r code_folding=TRUE, echo=TRUE}

data_pi = read.table("C:/Users/ange_/Downloads/My website/data.csv", sep = ";" , h = T)

```


#### Our data looks like this...


```{r layout="l-body-outset", echo=TRUE}
library(rmarkdown)
paged_table(data_pi)
```

#### Let's write the code


```{r fig.height=6, fig.width=10, layout="l-body-outset", preview=TRUE}

ggplot(data_pi, aes(x=Position, y=Pi, colour = Pi)) +
  
  geom_line() +
  
  scale_colour_gradient2(low = "#0000b3", mid = "#3333ff" , high = "#ff0000", midpoint=0.015) +
  
  geom_hline(yintercept=0.015, color="#00b300", size=.4, linetype = "dotted") +
  
  labs(y = expression(Nucleotide~diversity~(pi)), x = "Nucleotide position") +
  
  theme_minimal()+
  theme(panel.grid.major = element_line(colour = "grey", size = 0.2, linetype = "dotted")) +
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.2, linetype = "dotted")) +
  theme(plot.background = element_rect(colour = "white", size = 1))+
  theme(axis.text = element_text(colour = "black")) +
  
  scale_x_continuous(limits=c(0,155000),
  breaks = seq(0, 155000, by = 25000)) +
  scale_y_continuous(limits=c(0,0.035),
                     breaks = seq(0, 0.035, by = 0.005))

```






