---
title: "Genome assembly of Oryza sativa using PacBio Hifi dataset"
description: |
  PacBio Hifi assembly of rice genome.
author:
  - name: Yedomon Ange Bovys Zoclanclounon
    url: https://yedomon.netlify.app/
    affiliation: Jeonbuk National University
    affiliation_url: http://www.jbnu.ac.kr/eng/
    orcid_id: 0000-0003-2781-0778
date: 01-31-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    theme: theme.css
    name: "prepare-input-file-for-rnaediting-detection"
base_url: https://yedomon.netlify.app/posts/2021-01-31-genome-assembly-of-oryza-sativa-using-pacbio-hifi-dataset/
creative_commons: CC BY
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```




With the rise of long-reads sequencing technologies, it is now possible to get tens of Kb fragments reads.

Recently, the advent of high fidelity Pacbio long-reads drastically improve the accuracy of SMRT Sequencing platforms.


In this post, I will test the genome assembly of rice genome using Hifiasm assembler. 





### Installation

For the installation, I proceed like recommended by the developer.



```bash

$ sudo git clone https://github.com/chhylp123/hifiasm

$ cd hifiasm && make

```

Note: Make sure you have installed g++ and zlib dependencies.

I am using a Centos 7 distribution. So I installed zlib and g++ following the code:



```bash

$ sudo yum install gcc-c++


$ sudo yum install zlib-devel

```



### Data retrieving


For this assembly execution, I will use the rice O. sativa MH63 Hifi data available [here](ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR996/001/SRR9969481/SRR9969481_subreads.fastq.gz)

I grabbed the data set from European Nucleotide Archive [(ENA)](https://www.ebi.ac.uk/ena/browser/home) using the following accession number **SRR9969481**



```bash


# Download the data


$ wgetftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR996/001/SRR9969481/SRR9969481_subreads.fastq.gz


# Rename the data

$ mv SRR9969481_subreads.fastq.gz Rice.fastq.gz


# Create a link in my working directory


$ ln -fs ~/datafiles/002_o.sat.MH63_PacBio.HiFi.14kb/Rice.fastq.gz .


```




### Running



Using vim text editor I wrote a small bash script named run_hifiasm.sh:




```bash


#!/bin/bash

set -e


~/program/hifiasm/hifiasm -o Rice.asm -t 32 Rice.fastq.gz # assemble the genome



awk '/^S/{print ">"$2;print $3}' Rice.asm.p_ctg.gfa > Rice.asm.p_ctg.fa # get primary contigs in FASTA



```


Then I ran the bash using the following code:


```bash

$ /usr/bin/time -o out.ram.time.txt -v bash run_hifiasm.sh 2> log.hifiasm & 


```


Then I type *exit* to put in background the process.


### Results


Let's check the assembly sttistics


```bash

$ assembly-stats Rice.asm.p_ctg.fa


```


I have got the following assembly statistics:


```bash


sum = 421362451, n = 1225, ave = 343969.35, largest = 37513714
N50 = 13841853, n = 12
N60 = 13500458, n = 15
N70 = 12402620, n = 18
N80 = 10695965, n = 22
N90 = 5876907, n = 27
N100 = 8552, n = 1225
N_count = 0
Gaps = 0


```

Here are some characteristics related to the running process



```bash


Command being timed: "bash run_hifiasm.sh"
        User time (seconds): 108396.17
        System time (seconds): 1079.09
        Percent of CPU this job got: 2615%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:09:46
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 21640460
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 7
        Minor (reclaiming a frame) page faults: 269598163
        Voluntary context switches: 11845273
        Involuntary context switches: 1155532
        Swaps: 0
        File system inputs: 20530400
        File system outputs: 13984408
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0



```




### Comments


Hifiasm is incredibly fast. A total of **~18 mn** (system time) to assemble a **~430 Mb** [(Yu et al., 2002)](https://science.sciencemag.org/content/296/5565/79) genome with **32 cores**.


Table 1: Basics assembly statistics of R498 and MH63 assemblies

|                | MH63        | R498       | R498       |
| -------------- | ----------- | ---------- | ---------- |
| Data type      | PacBio hifi | PacBio CLR | PacBio CLR |
| Assembler      | Hifiasm     | CANU       | HERA       |
| Assembly level | Contigs     | Chromosome | Chromosome |
| Assembly size  | 421362451   | 390983850  | 391626037  |
| Contigs number | 1225        | 14         | 12         |
| Largest contig | 37513714    | 44361539   | 45881347   |
| N50            | 13841853    | 31778392   | 31347481   |
| L50            | 12          | 6          | 6          |



The peak memory was also low **21.64 MB**, showing that Hifiasm is less memory consuming. The Hifiasm assembly size was

**421 MB**, representing **97.90%** of the estimated size. Besides, the contiguity is incredibly high (N50 = 13.84 Mbp) compared to the recent Pacbio CLR, linkage mapping and fosmid-based assembly released by [**Du et al. 2017**](https://www.nature.com/articles/ncomms15324).A basic comparison with the chromosomal-scale assemblies from CANU  and HERA assemblers with PacBio CLR data (Table 1) showed that the Hifiasm assembly is quite good for Hi-C scaffolding. 






### Cited literature 


- [Yu et al. 2020 | A Draft Sequence of the Rice Genome (Oryza sativa L. ssp. indica)](https://science.sciencemag.org/content/296/5565/79)


- [Du et al. 2017 | Sequencing and de novo assembly of a near complete indica rice genome](https://www.nature.com/articles/ncomms15324#Tab2)


